### PR TITLE
More robust linting of files containing comments

### PR DESCRIPTION
**Pull request by harrysarson**
Hi, I made some improvements to `elm-lint`'s handling on comments and was wonding if you would be interested in an pull request.

- Moved the `removeComments` function out of `Lint.elm` (efba974) so that I could add tests in `RemoveCommentsTest.elm` (c17f70d).
- Fixed regexes in `removeComments` to properly find single line comments and also multiline comments (b277ddc).
- This caused the `NoWarningCommentsTest.elm` to fail as all the comments were removed so I made some changes to `Lint.elm`. Now the code attempts to pass the source file without removing comments and if that fails removes comments and trys again (2f682cf).

Please forgive me if I have reinvented the wheel anywhere here, this is my first pull request to an elm project so I am not super confident.

### CODE REVIEW

**Comment by harrysarson** [comment]
ping @jfmengels, would it be possible to take a look?

**Comment by jfmengels** [comment]
Hi @harrysarson!

I'm very sorry about the delay for my answer. I stopped working on this project for a while (because in my mind, it never worked to start with). I seem to understand you went with elm-analyse, and I'm happy you did so at the time.

I have started working on this project again, and I've rewritten almost everything. It is basically a whole new project now.
I have just [released a "closed" beta](https://jfmengels.net/announcing-elm-lint/), and if you are still interested in linting or tooling, I would appreciate your feedback :)

I'm closing this PR because these changes have become obsolete. I have now changed to using elm-syntax, which handles comments better than the elm-ast. Thank you for your interest though, and sorry for not coming back to you earlier :disappointed:

**Comment by harrysarson** [comment]
No worries, I am excited to see what the new version looks like!

**Comment by jfmengels** [comment]
You can take a look at https://jfmengels.net/announcing-elm-lint/, or see my post on the #elm-lint Slack channel :)

**Pull request closed without merging**
